REVOKE ALL ON TABLE cooperation_organization FROM PUBLIC;
REVOKE ALL ON TABLE cooperation_registration FROM PUBLIC;
REVOKE ALL ON TABLE cooperation_partner_status FROM PUBLIC;
REVOKE ALL ON TABLE cooperation_col_sequence FROM PUBLIC;
REVOKE ALL ON TABLE cooperation_admin_user FROM PUBLIC;
REVOKE ALL ON TABLE cooperation_audit_log FROM PUBLIC;

GRANT USAGE ON SCHEMA public TO __COOPERATION_RUNTIME_DATABASE_USER__;

GRANT SELECT, INSERT
  ON TABLE cooperation_organization
  TO __COOPERATION_RUNTIME_DATABASE_USER__;

GRANT SELECT, INSERT
  ON TABLE cooperation_registration
  TO __COOPERATION_RUNTIME_DATABASE_USER__;

GRANT SELECT, INSERT
  ON TABLE cooperation_partner_status
  TO __COOPERATION_RUNTIME_DATABASE_USER__;

GRANT SELECT, INSERT, UPDATE
  ON TABLE cooperation_col_sequence
  TO __COOPERATION_RUNTIME_DATABASE_USER__;

GRANT SELECT
  ON TABLE cooperation_admin_user
  TO __COOPERATION_RUNTIME_DATABASE_USER__;

GRANT INSERT
  ON TABLE cooperation_audit_log
  TO __COOPERATION_RUNTIME_DATABASE_USER__;
